async function main() {
  console.log("ðŸš© main()");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
